add_subdirectory(CodeEditorWidget)
add_subdirectory(CharactersModule)
add_subdirectory(ConsoleModule)
add_subdirectory(DatabaseModule)
add_subdirectory(FetchApiModule)
add_subdirectory(InventoriesModule)
add_subdirectory(MaterialsModule)
add_subdirectory(MessagerModule)
add_subdirectory(ShadersModule)
add_subdirectory(TexturesModule)
add_subdirectory(UsersModule)
